[package]
name = "aor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-integer = "0.1.45"
num-traits = "0.2.17"
regex = "1.10.2"
tqdm = "0.6.0"
ureq = "2.9.1"
